# Generated by Django 2.2.6 on 2019-10-11 19:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequests',
            fields=[
                ('loanNumber', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField(default=0)),
                ('dateCreated', models.DateField(default=django.utils.timezone.now)),
                ('dateApproved', models.DateField(blank=True, null=True)),
                ('dateSubmitted', models.DateField(blank=True, null=True)),
                ('dateDenied', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(default='United States', max_length=200, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zip', models.CharField(max_length=10, null=True)),
                ('loanNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LoanRequests')),
            ],
        ),
        migrations.CreateModel(
            name='LoanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=30, null=True)),
                ('amount', models.FloatField(default=0)),
                ('fico', models.IntegerField(default=0)),
                ('income', models.FloatField(default=0)),
                ('loanNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LoanRequests')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('loanNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LoanRequests')),
            ],
        ),
    ]
